version: "2"
services:
  client_dev:
    container_name: client
    restart: always
    build: ../client/
    image: client
    ports: 
      - "4200:4200"
    links:
      - server_dev
  server_dev:
    container_name: server_dev
    restart: always
    build: .
    image: server
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"